config/routes.rb
Rails.application.routes.draw do

  root 'www#index'

  get 'www/welcome'
  get 'www/show'
  get 'www/index'

  get 'www/quemsomos'
  get 'www/ensino0'
  get 'www/ensino1'
  get 'www/ensino2'
  get 'www/ensino3'
  get 'www/contactos'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/www_controller.rb
class WwwController < ApplicationController
  def welcome

  end

  def show
  end

  def index
    # Default Controller
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/www_helper.rb
module WwwHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoisTalentos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="_ntpnvT8_GS1jg_v5wEsTWfgEuoKTZ8IQiBi6hd7S84" />
</head>
<body>

<div align="center" id="menu" class="menu" style="/*border:dotted thin black;*/ height: 100px;">
  <%= link_to image_tag("logo0.png", alt: "Dois Talentos", title: "Dois Talentos: Clique para ir para a página inicial", width: "100px", style: "float:left;"), root_path %>
<br/><br/>
  <%= link_to("Início", www_welcome_path, class: "menu_items", id: "top_menu1", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("Quem Somos", www_quemsomos_path, class: "menu_items", id: "top_menu2", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("Ensino Primário", www_ensino0_path, class: "menu_items", id: "top_menu3", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("1º Ciclo", www_ensino1_path, class: "menu_items", id: "top_menu4", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("2º Ciclo", www_ensino2_path, class: "menu_items", id: "top_menu5", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("Técnico Profissional", www_ensino3_path, class: "menu_items", id: "top_menu6", style: 'font-family: \"Coming Soon,cursive;\"') %>
  <%= link_to("Contactos", www_contactos_path, class: "menu_items", id: "top_menu7", style: 'font-family: \"Coming Soon,cursive;\"') %>
</div>
<hr style="background-color: #b3cc05; height: 10px; color: #b3cc05; margin: 0; border: 0;" />

<%= yield %>

<br style="clear: both;" />
<footer>
  <div style="border-right:1px solid #cccccc; padding-left: 5px; padding-right: 45px;">
    &copy; 2014 Colégio Dois Talentos.<br/>
    Este website foi desenvolvido por <a href="http://www.linkedin.com/in/ivandosreisandrade" target="_blank" class="developer">Ivan dos Reis Andrade</a>.
  </div>
  <div style="border-right:1px solid #cccccc; width:140px; margin-left:45px; font-weight:bold;">
    <br/>
    Siga-nos
    <a href="https://www.facebook.com/colegiodoistalentos" target="_blank" class="icons sprite-fb" style="margin-left:10px">
    <%= image_tag("fb_icon_16.png") %>
    </a>
  </div>
  <div style="width:auto; margin-left:40px;">
    <span style="display:block;font-weight:bold;">Contactos Rápidos</span>
    <span style="padding:10px 0; border-right:1px solid #cccccc; padding-right:20px; margin-right:20px">
      <i class="icons sprite-phone"></i> <%= image_tag("ao_flag.gif", height: "15px", title: "Angola") %> (+244) 935 659 439</span>
    <span style="height:40px">
      geral@doistalentos.org</span>
  </div>
</footer>

</body>
</html>

app/views/www/contactos.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        $('#top_menu7').attr("class", "activated_menu_item");
    });
</script>

<div id="page-banner">
  Entre em contacto connosco
</div>
<div id="page">

  <!--<p style="border: dashed thin #cccccc; line-height: 150px; text-align: center;">GOOGLE MAP HERE...</p>-->
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62258.103558652496!2d15.74140425!3d-12.769972849999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1bb775b4dbf6dfdb%3A0x43a78822d1399cdb!2sHuambo%2C+Angola!5e0!3m2!1spt-PT!2s!4v1405972083393"
          width="1000" height="350" frameborder="0" style="border:0; padding-left: 12px"></iframe>
  <p>O nosso email: geral@doistalentos.org</p>
  <p>Contacto telefónico: <%= image_tag("ao_flag.gif", height: "15px", title: "Angola") %> (00244) 935 659 439 / 916 830 235</p>


</div>

app/views/www/ensino0.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        //$('#top_menu3').switchClass("menu_items", "activated_menu_item");
        $('#top_menu3').attr("class", "activated_menu_item");

        $('#sidebar').hcSticky({
            top: 20,
            bottomEnd: 100,
            wrapperClassName: 'sidebar-sticky'
        });


        // Cache selectors
        // topMenuHeight: serve para aumentar um espaço à pagina para o caso de se usar um menu fixo no topo da página
        var sideMenu = $("#sidebar"),
            //topMenuHeight = sideMenu.outerHeight()+20,
            topMenuHeight = 35,
        // All list items
            menuItems = sideMenu.find("a"),
        // Anchors corresponding to menu items
            scrollItems = menuItems.map(function(){
                var item = $($(this).attr("href"));
                if (item.length) { return item; }
            });

        // Bind click handler to menu items
        // so we can get a fancy scroll animation
        // AQUI deve-se subtrair a altura do topMenuHeight para causar o aumento do espaço: $(href).offset().top-topMenuHeight+1;
        menuItems.click(function(e){
            var href = $(this).attr("href"),
                offsetTop = href === "#" ? 0 : $(href).offset().top-topMenuHeight+1;
            $('html, body').stop().animate({
                scrollTop: offsetTop
            }, 500);
            e.preventDefault();
        });

        // Bind to scroll
        $(window).scroll(function(){
            // Get container scroll position
            var fromTop = $(this).scrollTop()+topMenuHeight;

            // Get id of current scroll item
            var cur = scrollItems.map(function(){
                if ($(this).offset().top < fromTop)
                    return this;
            });
            // Get the id of the current element
            cur = cur[cur.length-1];
            var id = cur && cur.length ? cur[0].id : "";
            // Set/remove active class
            menuItems
                    .parent().removeClass("active")
                    .end().filter("[href=#"+id+"]").parent().addClass("active");
        });

        $('.photogalery').cycle({
            fx: 'scrollup' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
        });
    });
</script>

<div id="page-banner">
    1ª, 2ª, 3ª e 4ª Classes
</div>

<div id="sidebar">
  <ul>
      <li><a href="#docentes">Docentes</a></li>
      <li><a href="#galeria">Galeria de Fotos</a></li>
      <li><a href="#projetos">Projectos</a></li>
      <li><a href="#servicos">Serviços</a></li>
  </ul>
</div>
<div id="sidebar-content">

  <h2 id="docentes">Docentes</h2>
  <p>É com muito orgulho que o Colégio Dois Talentos apresenta o elenco que toma conta dos mais novos da escola.</p>

  <h2>Professor &lt;NOME DO PROF 1&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 1&gt; é licenciado em Direito pela Faculdade de Direito da Universidade Agostinho Neto
    de Luanda. Tem mais de 3 anos de experiência na área da docência, e leciona várias cadeiras da área do Direito.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 2&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 2&gt; é licenciada em História pela Faculdade de Letras da Universidade Agostinho Neto
    de Luanda. Tem mais de 7 anos de experiência como funcionária pública no Ministério das Finanças. Leciona cadeiras da
    área de História.</p>
  <br/><br/>
  <h2>Professor &lt;NOME DO PROF 3&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 3&gt; é licenciado em Engenharia Informática pela Faculdade de Ciências da Universidade
    de Lisboa. Tem mais de 6 anos de experiência em programação web, e leciona cadeiras da área da Informática.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 4&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 4&gt; é licenciada em Arquitetura pela Faculdade de Belas Artes da Universidade
    Lusíada de Angola. Tem mais de 3 anos de experiência em consultoria de projetos de Arquitetura, e leciona cadeiras da
    área de artes plásticas e geografia.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="galeria">Galeria de Fotos</h2>
  <p>As nossas estrelas do primeiro ano.</p>
  <p>Sem imagens de momento...</p>
  <!--<div class="photogalery">
    <%= image_tag("panorama_historia_01.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_02.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_03.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_04.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_05.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_06.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_01.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_02.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_03.jpg", height: "300px", width: "100%", align:  "center") %>
  </div>-->
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="projetos">Projetos</h2>
  <p>Um dos projetos do Colégio Dois Talentos passa por proporcionar uma educação de excelência que seja acessível para
    a família tradicional Angolana.</p>
  <p>Também temos o projeto ABC, XYZ, etc...</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="servicos">Serviços</h2>
  <p>Os principais serviços do Colégio Dois Talentos estão ligados à área de ensino. Proporcionamos aos nossos estudantes
    uma formação com bases sólidas para que eles fiquem bem preparados para os anos seguintes. Oferecemos também formações
    complementares nas áreas da informática, desporto, música e jogos didáticos para que os nossos estudantes possam
    descontrair com actividades saudáveis. Acreditamos, que com estas actividades complementares os estudantes irão sempre
    motivados para a escola, aumentando assim a sua capacidade para absorver os conhecimentos passados pelos seus professores.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


</div>

app/views/www/ensino1.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        //$('#top_menu4').switchClass("menu_items", "activated_menu_item");
        $('#top_menu4').attr("class", "activated_menu_item");

        $('#sidebar').hcSticky({
            top: 20,
            bottomEnd: 100,
            wrapperClassName: 'sidebar-sticky'
        });


        // Cache selectors
        // topMenuHeight: serve para aumentar um espaço à pagina para o caso de se usar um menu fixo no topo da página
        var sideMenu = $("#sidebar"),
            //topMenuHeight = sideMenu.outerHeight()+20,
            topMenuHeight = 35,
        // All list items
            menuItems = sideMenu.find("a"),
        // Anchors corresponding to menu items
            scrollItems = menuItems.map(function(){
                var item = $($(this).attr("href"));
                if (item.length) { return item; }
            });

        // Bind click handler to menu items
        // so we can get a fancy scroll animation
        // AQUI deve-se subtrair a altura do topMenuHeight para causar o aumento do espaço: $(href).offset().top-topMenuHeight+1;
        menuItems.click(function(e){
            var href = $(this).attr("href"),
                offsetTop = href === "#" ? 0 : $(href).offset().top-topMenuHeight+1;
            $('html, body').stop().animate({
                scrollTop: offsetTop
            }, 500);
            e.preventDefault();
        });

        // Bind to scroll
        $(window).scroll(function(){
            // Get container scroll position
            var fromTop = $(this).scrollTop()+topMenuHeight;

            // Get id of current scroll item
            var cur = scrollItems.map(function(){
                if ($(this).offset().top < fromTop)
                    return this;
            });
            // Get the id of the current element
            cur = cur[cur.length-1];
            var id = cur && cur.length ? cur[0].id : "";
            // Set/remove active class
            menuItems
                    .parent().removeClass("active")
                    .end().filter("[href=#"+id+"]").parent().addClass("active");
        });

        $('.photogalery').cycle({
            fx: 'scrollup' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
        });
    });
</script>

<div id="page-banner">
    5ª e 6ª Classes
</div>

<div id="sidebar">
  <ul>
      <li><a href="#docentes">Docentes</a></li>
      <li><a href="#galeria">Galeria de Fotos</a></li>
      <li><a href="#projetos">Projectos</a></li>
      <li><a href="#servicos">Serviços</a></li>
  </ul>
</div>
<div id="sidebar-content">

  <h2 id="docentes">Docentes</h2>
  <p>É com muito orgulho que o Colégio Dois Talentos apresenta o elenco que toma conta dos iniciados aos finalistas do 1º ciclo.</p>

  <h2>Professor &lt;NOME DO PROF 1&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 1&gt; é licenciado em Direito pela Faculdade de Direito da Universidade Agostinho Neto
    de Luanda. Tem mais de 3 anos de experiência na área da docência, e leciona várias cadeiras da área do Direito.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 2&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 2&gt; é licenciada em História pela Faculdade de Letras da Universidade Agostinho Neto
    de Luanda. Tem mais de 7 anos de experiência como funcionária pública no Ministério das Finanças. Leciona cadeiras da
    área de História.</p>
  <br/><br/>
  <h2>Professor &lt;NOME DO PROF 3&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 3&gt; é licenciado em Engenharia Informática pela Faculdade de Ciências da Universidade
    de Lisboa. Tem mais de 6 anos de experiência em programação web, e leciona cadeiras da área da Informática.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 4&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 4&gt; é licenciada em Arquitetura pela Faculdade de Belas Artes da Universidade
    Lusíada de Angola. Tem mais de 3 anos de experiência em consultoria de projetos de Arquitetura, e leciona cadeiras da
    área de artes plásticas e geografia.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="galeria">Galeria de Fotos</h2>
  <p>As nossas estrelas do primeiro ciclo.</p>
  <p>Sem imagens de momento...</p>
<!--  <div class="photogalery">
    <%= image_tag("panorama_historia_01.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_02.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_03.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_04.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_05.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_06.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_01.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_02.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_03.jpg", height: "300px", width: "100%", align:  "center") %>
  </div>-->
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="projetos">Projetos</h2>
  <p>Um dos projetos do Colégio Dois Talentos passa por proporcionar uma educação de excelência que seja acessível para
    a família tradicional Angolana.</p>
  <p>Também temos o projeto ABC, XYZ, etc...</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="servicos">Serviços</h2>
  <p>Os principais serviços do Colégio Dois Talentos estão ligados à área de ensino. Proporcionamos aos nossos estudantes
    uma formação com bases sólidas para que eles fiquem bem preparados para os anos seguintes. Oferecemos também formações
    complementares nas áreas da informática, desporto, música e jogos didáticos para que os nossos estudantes possam
    descontrair com actividades saudáveis. Acreditamos, que com estas actividades complementares os estudantes irão sempre
    motivados para a escola, aumentando assim a sua capacidade para absorver os conhecimentos passados pelos seus professores.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


</div>

app/views/www/ensino2.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        //$('#top_menu5').switchClass("menu_items", "activated_menu_item");
        $('#top_menu5').attr("class", "activated_menu_item");

        $('#sidebar').hcSticky({
            top: 20,
            bottomEnd: 100,
            wrapperClassName: 'sidebar-sticky'
        });


        // Cache selectors
        // topMenuHeight: serve para aumentar um espaço à pagina para o caso de se usar um menu fixo no topo da página
        var sideMenu = $("#sidebar"),
            //topMenuHeight = sideMenu.outerHeight()+20,
            topMenuHeight = 35,
        // All list items
            menuItems = sideMenu.find("a"),
        // Anchors corresponding to menu items
            scrollItems = menuItems.map(function(){
                var item = $($(this).attr("href"));
                if (item.length) { return item; }
            });

        // Bind click handler to menu items
        // so we can get a fancy scroll animation
        // AQUI deve-se subtrair a altura do topMenuHeight para causar o aumento do espaço: $(href).offset().top-topMenuHeight+1;
        menuItems.click(function(e){
            var href = $(this).attr("href"),
                offsetTop = href === "#" ? 0 : $(href).offset().top-topMenuHeight+1;
            $('html, body').stop().animate({
                scrollTop: offsetTop
            }, 500);
            e.preventDefault();
        });

        // Bind to scroll
        $(window).scroll(function(){
            // Get container scroll position
            var fromTop = $(this).scrollTop()+topMenuHeight;

            // Get id of current scroll item
            var cur = scrollItems.map(function(){
                if ($(this).offset().top < fromTop)
                    return this;
            });
            // Get the id of the current element
            cur = cur[cur.length-1];
            var id = cur && cur.length ? cur[0].id : "";
            // Set/remove active class
            menuItems
                    .parent().removeClass("active")
                    .end().filter("[href=#"+id+"]").parent().addClass("active");
        });

        $('.photogalery').cycle({
            fx: 'scrollup' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
        });
    });
</script>

<div id="page-banner">
    7ª, 8ª e 9ª Classes
</div>

<div id="sidebar">
  <ul>
      <li><a href="#docentes">Docentes</a></li>
      <li><a href="#galeria">Galeria de Fotos</a></li>
      <li><a href="#projetos">Projectos</a></li>
      <li><a href="#servicos">Serviços</a></li>
  </ul>
</div>
<div id="sidebar-content">

  <h2 id="docentes">Docentes</h2>
  <p>É com muito orgulho que o Colégio Dois Talentos apresenta o elenco que toma conta dos iniciados aos finalistas do 2º ciclo.</p>

  <h2>Professor &lt;NOME DO PROF 1&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 1&gt; é licenciado em Direito pela Faculdade de Direito da Universidade Agostinho Neto
    de Luanda. Tem mais de 3 anos de experiência na área da docência, e leciona várias cadeiras da área do Direito.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 2&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 2&gt; é licenciada em História pela Faculdade de Letras da Universidade Agostinho Neto
    de Luanda. Tem mais de 7 anos de experiência como funcionária pública no Ministério das Finanças. Leciona cadeiras da
    área de História.</p>
  <br/><br/>
  <h2>Professor &lt;NOME DO PROF 3&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    O professor &lt;NOME DO PROF 3&gt; é licenciado em Engenharia Informática pela Faculdade de Ciências da Universidade
    de Lisboa. Tem mais de 6 anos de experiência em programação web, e leciona cadeiras da área da Informática.</p>
  <br/><br/>
  <h2>Professora &lt;NOME DO PROF 4&gt;</h2>
  <p><%= image_tag("ao_flag.gif", height: "80px", width: "80px", style: "float:left; margin-right:5px;") %>
    A professora &lt;NOME DO PROF 4&gt; é licenciada em Arquitetura pela Faculdade de Belas Artes da Universidade
    Lusíada de Angola. Tem mais de 3 anos de experiência em consultoria de projetos de Arquitetura, e leciona cadeiras da
    área de artes plásticas e geografia.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="galeria">Galeria de Fotos</h2>
  <p>As nossas estrelas do segundo ciclo.</p>
  <p>Sem imagens de momento...</p>
<!--  <div class="photogalery">
    <%= image_tag("panorama_historia_01.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_02.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_03.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_04.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_05.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("panorama_historia_06.png", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_01.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_02.jpg", height: "300px", width: "100%", align:  "center") %>
    <%= image_tag("historia_03.jpg", height: "300px", width: "100%", align:  "center") %>
  </div>-->
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="projetos">Projetos</h2>
  <p>Um dos projetos do Colégio Dois Talentos passa por proporcionar uma educação de excelência que seja acessível para
    a família tradicional Angolana.</p>
  <p>Também temos o projeto ABC, XYZ, etc...</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


  <h2 id="servicos">Serviços</h2>
  <p>Os principais serviços do Colégio Dois Talentos estão ligados à área de ensino. Proporcionamos aos nossos estudantes
    uma formação com bases sólidas para que eles fiquem bem preparados para os anos seguintes. Oferecemos também formações
    complementares nas áreas da informática, desporto, música e jogos didáticos para que os nossos estudantes possam
    descontrair com actividades saudáveis. Acreditamos, que com estas actividades complementares os estudantes irão sempre
    motivados para a escola, aumentando assim a sua capacidade para absorver os conhecimentos passados pelos seus professores.</p>
  <br/><br/><br/><br/><br/><br/><br/><br/>


</div>

app/views/www/index.html.erb
<div id="page">
  <div align="center">
    <%= link_to(image_tag("logo0.png", alt: "Dois Talentos", title: "Dois Talentos: Clique Para Entrar", class: "brandLogo"), www_welcome_path) %>
  </div>
  <div id="contactsInfo">
    Telf.: <%= image_tag("ao_flag.gif", height: "15px", title: "Angola") %> (+244) 935 659 439 / 916 830 235<br>
    <br>
    Morada: Rua de São João, s/nº, Bairro São João Popular. Huambo - Angola<br>
    Website: www.doistalentos.org<br>
    Email: geral@doistalentos.org<br>
  </div>
</div>

app/views/www/show.html.erb
<h1>Www#show</h1>
<p>Find me in app/views/www/show.html.erb</p>